// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: bank/v1beta1/balance.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wrapper to store balances in KVStore
type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coins         string                 `protobuf:"bytes,1,opt,name=coins,proto3" json:"coins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_bank_v1beta1_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_bank_v1beta1_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_bank_v1beta1_balance_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetCoins() string {
	if x != nil {
		return x.Coins
	}
	return ""
}

var File_bank_v1beta1_balance_proto protoreflect.FileDescriptor

const file_bank_v1beta1_balance_proto_rawDesc = "" +
	"\n" +
	"\x1abank/v1beta1/balance.proto\x12\fbank.v1beta1\"\x1f\n" +
	"\aBalance\x12\x14\n" +
	"\x05coins\x18\x01 \x01(\tR\x05coinsB2Z0github.com/your-username/cosmosbank/x/bank/typesb\x06proto3"

var (
	file_bank_v1beta1_balance_proto_rawDescOnce sync.Once
	file_bank_v1beta1_balance_proto_rawDescData []byte
)

func file_bank_v1beta1_balance_proto_rawDescGZIP() []byte {
	file_bank_v1beta1_balance_proto_rawDescOnce.Do(func() {
		file_bank_v1beta1_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_v1beta1_balance_proto_rawDesc), len(file_bank_v1beta1_balance_proto_rawDesc)))
	})
	return file_bank_v1beta1_balance_proto_rawDescData
}

var file_bank_v1beta1_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bank_v1beta1_balance_proto_goTypes = []any{
	(*Balance)(nil), // 0: bank.v1beta1.Balance
}
var file_bank_v1beta1_balance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bank_v1beta1_balance_proto_init() }
func file_bank_v1beta1_balance_proto_init() {
	if File_bank_v1beta1_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_v1beta1_balance_proto_rawDesc), len(file_bank_v1beta1_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bank_v1beta1_balance_proto_goTypes,
		DependencyIndexes: file_bank_v1beta1_balance_proto_depIdxs,
		MessageInfos:      file_bank_v1beta1_balance_proto_msgTypes,
	}.Build()
	File_bank_v1beta1_balance_proto = out.File
	file_bank_v1beta1_balance_proto_goTypes = nil
	file_bank_v1beta1_balance_proto_depIdxs = nil
}
