// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: bank/v1beta1/msg.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgSend represents a message to send coins from one account to another.
type MsgSend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   string                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"` // Sender address
	ToAddress     string                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`       // Recipient address
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`                              // Amount to send, represented as a string for simplicity
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSend) Reset() {
	*x = MsgSend{}
	mi := &file_bank_v1beta1_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSend) ProtoMessage() {}

func (x *MsgSend) ProtoReflect() protoreflect.Message {
	mi := &file_bank_v1beta1_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSend.ProtoReflect.Descriptor instead.
func (*MsgSend) Descriptor() ([]byte, []int) {
	return file_bank_v1beta1_msg_proto_rawDescGZIP(), []int{0}
}

func (x *MsgSend) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *MsgSend) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *MsgSend) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// MsgSendResponse defines the response structure for MsgSend.
type MsgSendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSendResponse) Reset() {
	*x = MsgSendResponse{}
	mi := &file_bank_v1beta1_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSendResponse) ProtoMessage() {}

func (x *MsgSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_v1beta1_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSendResponse.ProtoReflect.Descriptor instead.
func (*MsgSendResponse) Descriptor() ([]byte, []int) {
	return file_bank_v1beta1_msg_proto_rawDescGZIP(), []int{1}
}

var File_bank_v1beta1_msg_proto protoreflect.FileDescriptor

const file_bank_v1beta1_msg_proto_rawDesc = "" +
	"\n" +
	"\x16bank/v1beta1/msg.proto\x12\fbank.v1beta1\"c\n" +
	"\aMsgSend\x12!\n" +
	"\ffrom_address\x18\x01 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\x02 \x01(\tR\ttoAddress\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"\x11\n" +
	"\x0fMsgSendResponse2C\n" +
	"\x03Msg\x12<\n" +
	"\x04Send\x12\x15.bank.v1beta1.MsgSend\x1a\x1d.bank.v1beta1.MsgSendResponseB/Z-github.com/similadayo/cosmosbank/x/bank/typesb\x06proto3"

var (
	file_bank_v1beta1_msg_proto_rawDescOnce sync.Once
	file_bank_v1beta1_msg_proto_rawDescData []byte
)

func file_bank_v1beta1_msg_proto_rawDescGZIP() []byte {
	file_bank_v1beta1_msg_proto_rawDescOnce.Do(func() {
		file_bank_v1beta1_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_v1beta1_msg_proto_rawDesc), len(file_bank_v1beta1_msg_proto_rawDesc)))
	})
	return file_bank_v1beta1_msg_proto_rawDescData
}

var file_bank_v1beta1_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bank_v1beta1_msg_proto_goTypes = []any{
	(*MsgSend)(nil),         // 0: bank.v1beta1.MsgSend
	(*MsgSendResponse)(nil), // 1: bank.v1beta1.MsgSendResponse
}
var file_bank_v1beta1_msg_proto_depIdxs = []int32{
	0, // 0: bank.v1beta1.Msg.Send:input_type -> bank.v1beta1.MsgSend
	1, // 1: bank.v1beta1.Msg.Send:output_type -> bank.v1beta1.MsgSendResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bank_v1beta1_msg_proto_init() }
func file_bank_v1beta1_msg_proto_init() {
	if File_bank_v1beta1_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_v1beta1_msg_proto_rawDesc), len(file_bank_v1beta1_msg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_v1beta1_msg_proto_goTypes,
		DependencyIndexes: file_bank_v1beta1_msg_proto_depIdxs,
		MessageInfos:      file_bank_v1beta1_msg_proto_msgTypes,
	}.Build()
	File_bank_v1beta1_msg_proto = out.File
	file_bank_v1beta1_msg_proto_goTypes = nil
	file_bank_v1beta1_msg_proto_depIdxs = nil
}
