// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: bank/v1beta1/query.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryBalanceRequest defines request type for balance query.
type QueryBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBalanceRequest) Reset() {
	*x = QueryBalanceRequest{}
	mi := &file_bank_v1beta1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBalanceRequest) ProtoMessage() {}

func (x *QueryBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bank_v1beta1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBalanceRequest.ProtoReflect.Descriptor instead.
func (*QueryBalanceRequest) Descriptor() ([]byte, []int) {
	return file_bank_v1beta1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryBalanceRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// QueryBalanceResponse defines response type for balance query.
type QueryBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       string                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"` // e.g., "1000atom"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryBalanceResponse) Reset() {
	*x = QueryBalanceResponse{}
	mi := &file_bank_v1beta1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryBalanceResponse) ProtoMessage() {}

func (x *QueryBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bank_v1beta1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryBalanceResponse.ProtoReflect.Descriptor instead.
func (*QueryBalanceResponse) Descriptor() ([]byte, []int) {
	return file_bank_v1beta1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

var File_bank_v1beta1_query_proto protoreflect.FileDescriptor

const file_bank_v1beta1_query_proto_rawDesc = "" +
	"\n" +
	"\x18bank/v1beta1/query.proto\x12\fbank.v1beta1\"/\n" +
	"\x13QueryBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"0\n" +
	"\x14QueryBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\tR\abalance2Y\n" +
	"\x05Query\x12P\n" +
	"\aBalance\x12!.bank.v1beta1.QueryBalanceRequest\x1a\".bank.v1beta1.QueryBalanceResponseB/Z-github.com/similadayo/cosmosbank/x/bank/typesb\x06proto3"

var (
	file_bank_v1beta1_query_proto_rawDescOnce sync.Once
	file_bank_v1beta1_query_proto_rawDescData []byte
)

func file_bank_v1beta1_query_proto_rawDescGZIP() []byte {
	file_bank_v1beta1_query_proto_rawDescOnce.Do(func() {
		file_bank_v1beta1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bank_v1beta1_query_proto_rawDesc), len(file_bank_v1beta1_query_proto_rawDesc)))
	})
	return file_bank_v1beta1_query_proto_rawDescData
}

var file_bank_v1beta1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bank_v1beta1_query_proto_goTypes = []any{
	(*QueryBalanceRequest)(nil),  // 0: bank.v1beta1.QueryBalanceRequest
	(*QueryBalanceResponse)(nil), // 1: bank.v1beta1.QueryBalanceResponse
}
var file_bank_v1beta1_query_proto_depIdxs = []int32{
	0, // 0: bank.v1beta1.Query.Balance:input_type -> bank.v1beta1.QueryBalanceRequest
	1, // 1: bank.v1beta1.Query.Balance:output_type -> bank.v1beta1.QueryBalanceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bank_v1beta1_query_proto_init() }
func file_bank_v1beta1_query_proto_init() {
	if File_bank_v1beta1_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bank_v1beta1_query_proto_rawDesc), len(file_bank_v1beta1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bank_v1beta1_query_proto_goTypes,
		DependencyIndexes: file_bank_v1beta1_query_proto_depIdxs,
		MessageInfos:      file_bank_v1beta1_query_proto_msgTypes,
	}.Build()
	File_bank_v1beta1_query_proto = out.File
	file_bank_v1beta1_query_proto_goTypes = nil
	file_bank_v1beta1_query_proto_depIdxs = nil
}
